### ISSUE TITLE
希望新增Movie-Bot设置的豆瓣Cookie接口

### ISSUE THREAD

**Issue by WWWWM03** [pofey/movie-bot-api#1]
在一些豆瓣相关的场景下，比如查询多页豆单、看过及评分回写均需要Cookie进行操作，希望可以开放豆瓣Cookie的接口。后续加入在请求头中进行访问。

**Comment by pofey** [comment]
你是说直接读机器人里配置过的豆瓣cookie吧，拿到 然后去模拟请求

**Comment by WWWWM03** [comment]
对的衣总
